name: Meu Primeiro WorkFlow no GitHub Actions

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  job01:
    runs-on: ubuntu_latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
      - run: echo Teste do Mac! 
  
